name: GameOfLife
version: 1.0.0
main: it.tristana.gameoflife.Main
description: Simple game of life
author: Massimiliano Micol
api-version: 1.20
depend: [TristanaCommons, WorldEdit]
softdepend: [FastAsyncWorldEdit]
commands:
  gol:
    description: Main command
    usage: Type /gol help
    permission: gameoflife.admin
    default: op